[project]
name = "pwpw-protocol"
version = "0.1.0"
dependencies = [
    "pwpw-common"
]

[tool.uv.sources]
pwpw-common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
